<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.z03Akqp' shared service.

return $this->privates['.service_locator.z03Akqp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\LoginController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\WarriController::allus' => ['privates', '.service_locator.2bmvfb0', 'get_ServiceLocator_2bmvfb0Service.php', true],
    'App\\Controller\\WarriController::oneus' => ['privates', '.service_locator.2bmvfb0', 'get_ServiceLocator_2bmvfb0Service.php', true],
    'App\\Controller\\WarriController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\LoginController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\WarriController:allus' => ['privates', '.service_locator.2bmvfb0', 'get_ServiceLocator_2bmvfb0Service.php', true],
    'App\\Controller\\WarriController:oneus' => ['privates', '.service_locator.2bmvfb0', 'get_ServiceLocator_2bmvfb0Service.php', true],
    'App\\Controller\\WarriController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\LoginController::register' => '?',
    'App\\Controller\\WarriController::allus' => '?',
    'App\\Controller\\WarriController::oneus' => '?',
    'App\\Controller\\WarriController::register' => '?',
    'App\\Controller\\LoginController:register' => '?',
    'App\\Controller\\WarriController:allus' => '?',
    'App\\Controller\\WarriController:oneus' => '?',
    'App\\Controller\\WarriController:register' => '?',
]);
