<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKXAcayi\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKXAcayi/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKXAcayi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKXAcayi\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerKXAcayi\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'KXAcayi',
    'container.build_id' => 'd2da9dd0',
    'container.build_time' => 1564568509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKXAcayi');
