<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerBlDZ5LM\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBlDZ5LM/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBlDZ5LM.legacy');
=======
if (\class_exists(\ContainerHWMPLMw\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHWMPLMw/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHWMPLMw.legacy');
>>>>>>> 1c96c272bdbe28df722d618568999c3bbf163423

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerBlDZ5LM\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerBlDZ5LM\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'BlDZ5LM',
    'container.build_id' => '708ca3bb',
    'container.build_time' => 1564489461,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBlDZ5LM');
=======
    \class_alias(\ContainerHWMPLMw\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerHWMPLMw\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'HWMPLMw',
    'container.build_id' => 'bd5ab8d2',
    'container.build_time' => 1564561567,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHWMPLMw');
>>>>>>> 1c96c272bdbe28df722d618568999c3bbf163423
