<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMAiSWkX\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMAiSWkX/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMAiSWkX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMAiSWkX\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerMAiSWkX\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'MAiSWkX',
    'container.build_id' => '26079c97',
    'container.build_time' => 1564476051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMAiSWkX');
