<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjRsMki\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjRsMki/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQjRsMki.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQjRsMki\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQjRsMki\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QjRsMki',
    'container.build_id' => '37401352',
    'container.build_time' => 1564259197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjRsMki');
