<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC5QCBtp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC5QCBtp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC5QCBtp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC5QCBtp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerC5QCBtp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'C5QCBtp',
    'container.build_id' => '7619add2',
    'container.build_time' => 1564579601,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC5QCBtp');
