<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYqHRcXd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYqHRcXd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYqHRcXd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYqHRcXd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYqHRcXd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YqHRcXd',
    'container.build_id' => 'a077e946',
    'container.build_time' => 1564391221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYqHRcXd');
